# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pnpzR358Eh1mXYaeUaVgVRSLPaNg24TX
"""

def telefon(rusmi):
  if rusmi=="redmi note 12":
    return "narxi 1.200.000"
  elif rusmi=="redmi note 13 pro ":

    return "narxi: 4.200.000"
  elif rusmi=="iphone 16 pro max":

    return "narxi: 25.000.000"
  elif rusmi=="Honor 200 lite ":

    return "narxi: 5.400.000"
  elif rusmi=="infinix GT 20 pro":

    return "narxi: 5.000.000"
  elif rusmi=="iphone 14 pro max":

    return "narxi: 10.000.000"
  elif rusmi=="poco F6 pro ":

    return "narxi: 6.000.000"
  elif rusmi=="redmegic 7 pro":

    return "narxi: 9.000.000"
  else:
    return "Telefon haqida ma'lumot kerak bo'lsa bizga murojat qiling"
rusmi= input("Telefon markasini kiriting:")
natija=telefon(rusmi)
print(natija)